import { dotlayer } from "./common";
const smallTitleAttr = {
  w: 153,
  h: 42
}

const bgConfig = {
  layers: {
    customBackground_1: {
      id: "customBackground_1",
      type: "com",
      attr: {
        x: 20,
        y: 120,
        w: 486, 
        h: 296,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 1,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_2: {
      id: "customBackground_2",
      type: "com",
      attr: {
        x: 20,
        y: 440,
        w: 486,
        h: 296,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 1,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_3: {
      id: "customBackground_3",
      type: "com",
      attr: {
        x: 20,
        y: 760,
        w: 486,
        h: 296,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 1,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_4: {
      id: "customBackground_4",
      type: "com",
      attr: {
        x: 530,
        y: 145,
        w: 855,
        h: 619,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 2,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_5: {
      id: "customBackground_5",
      type: "com",
      attr: {
        x: 530,
        y: 784,
        w: 855,
        h: 276,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 3,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_6: {
      id: "customBackground_6",
      type: "com",
      attr: {
        x: 1405,
        y: 82,
        w: 495,
        h: 310,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 4,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_7: {
      id: "customBackground_7",
      type: "com",
      attr: {
        x: 1405,
        y: 412,
        w: 495,
        h: 460,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 5,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_8: {
      id: "customBackground_8",
      type: "com",
      attr: {
        x: 1405,
        y: 892,
        w: 495,
        h: 168,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 6,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_9: {
      id: "customBackground_9",
      type: "com",
      attr: {
        x: 0,
        y: 0,
        w: 1920,
        h: 96,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 8,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_10: {
      id: "customBackground_10",
      type: "com",
      attr: {
        x: 32,
        y: 132,
        w: smallTitleAttr.w,
        h: smallTitleAttr.h,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 9,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_11: {
      id: "customBackground_11",
      type: "com",
      attr: {
        x: 32,
        y: 252,
        w: smallTitleAttr.w,
        h: smallTitleAttr.h,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 9,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_12: {
      id: "customBackground_12",
      type: "com",
      attr: {
        x: 32,
        y: 452,
        w: smallTitleAttr.w,
        h: smallTitleAttr.h,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 9,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_13: {
      id: "customBackground_13",
      type: "com",
      attr: {
        x: 32,
        y: 571,
        w: smallTitleAttr.w,
        h: smallTitleAttr.h,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 9,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_14: {
      id: "customBackground_14",
      type: "com",
      attr: {
        x: 32,
        y: 772,
        w: smallTitleAttr.w,
        h: smallTitleAttr.h,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 9,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_15: {
      id: "customBackground_15",
      type: "com",
      attr: {
        x: 32,
        y: 891,
        w: smallTitleAttr.w,
        h: smallTitleAttr.h,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 9,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_16: {
      id: "customBackground_16",
      type: "com",
      attr: {
        x: 1417,
        y: 94,
        w: smallTitleAttr.w,
        h: smallTitleAttr.h,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 9,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_17: {
      id: "customBackground_17",
      type: "com",
      attr: {
        x: 542,
        y: 132,
        w: smallTitleAttr.w,
        h: smallTitleAttr.h,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 9,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_18: {
      id: "customBackground_18",
      type: "com",
      attr: {
        x: 1417,
        y: 904,
        w: smallTitleAttr.w,
        h: smallTitleAttr.h,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 9,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_19: {
      id: "customBackground_19",
      type: "com",
      attr: {
        x: 542,
        y: 796,
        w: 216,
        h: 42,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 10,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_20: {
      id: "customBackground_20",
      type: "com",
      attr: {
        x: 771,
        y: 84,
        w: 384,
        h: 50,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 11,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_21: {
      id: "customBackground_21",
      type: "com",
      attr: {
        x: 530,
        y: 120,
        w: 420,
        h: 300,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 12,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_22: {
      id: "customBackground_22",
      type: "com",
      attr: {
        x: 970,
        y: 120,
        w: 420,
        h: 300,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 12,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_23: {
      id: "customBackground_23",
      type: "com",
      attr: {
        x: 982,
        y: 132,
        w: smallTitleAttr.w,
        h: smallTitleAttr.h,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 9,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_24: {
      id: "customBackground_24",
      type: "com",
      attr: {
        x: 530,
        y: 440,
        w: 420,
        h: 300,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 12,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_25: {
      id: "customBackground_25",
      type: "com",
      attr: {
        x: 970,
        y: 440,
        w: 420,
        h: 300,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 12,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_26: {
      id: "customBackground_26",
      type: "com",
      attr: {
        x: 542,
        y: 452,
        w: smallTitleAttr.w,
        h: smallTitleAttr.h,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 9,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_27: {
      id: "customBackground_27",
      type: "com",
      attr: {
        x: 982,
        y: 452,
        w: smallTitleAttr.w,
        h: smallTitleAttr.h,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 9,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_28: {
      id: "customBackground_28",
      type: "com",
      attr: {
        x: 653,
        y: 810,
        w: 614,
        h: 250,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 16,
      },
      data: {},
      version: "0.0.12",
    },
    customBackground_29: {
      id: "customBackground_29",
      type: "com",
      attr: {
        x: 20,
        y: 274,
        w: 614,
        h: 142,
        opacity: 1,
      },
      comName: "customBackground",
      requirePath: "CustomBackground",
      config: {
        typeNo: 16,
      },
      data: {},
      version: "0.0.12",
    },
    decorate_dot_1: {
      ...dotlayer,
      id: "decorate_dot_1",
      attr: {
        x: 669,
        y: 836,
        w: 14,
        h: 14,
        opacity: 1,
      },
    },
    decorate_dot_2: {
      ...dotlayer,
      id: "decorate_dot_2",
      attr: {
        x: 36,
        y: 294,
        w: 14,
        h: 14,
        opacity: 1,
      },
    },
  },
  zIndexList: [
    // { id: "customBackground_1", type: "com" },
    // { id: "customBackground_2", type: "com" },
    // { id: "customBackground_3", type: "com" },
    // { id: "customBackground_4", type: "com" },
    // { id: "customBackground_5", type: "com" },
    // { id: "customBackground_6", type: "com" },
    // { id: "customBackground_7", type: "com" },
    // { id: "customBackground_8", type: "com" },
    // { id: "customBackground_9", type: "com" },
    // { id: "customBackground_10", type: "com" },
    // { id: "customBackground_11", type: "com" },
    // { id: "customBackground_12", type: "com" },
    // { id: "customBackground_13", type: "com" },
    // { id: "customBackground_14", type: "com" },
    // { id: "customBackground_15", type: "com" },
    // { id: "customBackground_16", type: "com" },
    
    // { id: "customBackground_18", type: "com" },
    // { id: "customBackground_19", type: "com" },
    // // { id: "customBackground_20", type: "com" },
    // { id: "customBackground_21", type: "com" },
    // { id: "customBackground_22", type: "com" },
    // { id: "customBackground_24", type: "com" },
    // { id: "customBackground_25", type: "com" },
    // { id: "customBackground_17", type: "com" },
    // { id: "customBackground_23", type: "com" },
    // { id: "customBackground_26", type: "com" },
    // { id: "customBackground_27", type: "com" },
    { id: "customBackground_28", type: "com" },
    { id: "customBackground_29", type: "com" },
    { id: "decorate_dot_1", type: "com" },
    { id: "decorate_dot_2", type: "com" },

    
  ],
};
export default bgConfig;
